/** Validation schemas barrel (Zod). One schema module per entity. */
export * from '@/lib/validation/common.schema'
export * from '@/lib/validation/client.schema'
export * from '@/lib/validation/product.schema'
export * from '@/lib/validation/template.schema'
export * from '@/lib/validation/user.schema'
export * from '@/lib/validation/workspace.schema'
export * from '@/lib/validation/plan.schema'
export * from '@/lib/validation/notification.schema'
export * from '@/lib/validation/file.schema'
export * from '@/lib/validation/payment.schema'
export * from '@/lib/validation/invoice.schema'
export * from '@/lib/validation/auth.schema'
export * from '@/lib/validation/document.schema'
