// Auth UI text and flow data

export const authTexts = {
  signIn: {
    title: 'Welcome back',
    subtitle: 'Sign in to your ToolForge account',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signInButton: 'Sign in',
    signUpLink: "Don't have an account? Sign up",
    divider: 'Or continue with',
    google: 'Continue with Google',
    github: 'Continue with GitHub',
  },
  signUp: {
    title: 'Create your account',
    subtitle: 'Join ToolForge and start generating invoices',
    nameLabel: 'Full name',
    namePlaceholder: 'John Doe',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    confirmLabel: 'Confirm password',
    confirmPlaceholder: '••••••••',
    agreeTerms: 'I agree to the Terms of Service and Privacy Policy',
    signUpButton: 'Create account',
    signInLink: 'Already have an account? Sign in',
    divider: 'Or continue with',
    google: 'Continue with Google',
    github: 'Continue with GitHub',
  },
  forgotPassword: {
    title: 'Forgot password?',
    subtitle: 'Enter your email address and we will send you a password reset link.',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    sendButton: 'Send reset link',
    backToSignIn: 'Back to sign in',
  },
  resetPassword: {
    title: 'Reset your password',
    subtitle: 'Enter your new password below.',
    passwordLabel: 'New password',
    passwordPlaceholder: '••••••••',
    confirmLabel: 'Confirm password',
    confirmPlaceholder: '••••••••',
    resetButton: 'Reset password',
    backToSignIn: 'Back to sign in',
  },
  verifyEmail: {
    title: 'Verify your email',
    subtitle: 'We sent a code to your email address',
    codeLabel: 'Verification code',
    codePlaceholder: '000000',
    verifyButton: 'Verify email',
    resendCode: "Didn't receive the code? Resend",
    backToSignIn: 'Back to sign in',
  },
  twoFactor: {
    title: 'Two-factor authentication',
    subtitle: 'Enter the code from your authenticator app',
    codeLabel: 'Authentication code',
    codePlaceholder: '000000',
    verifyButton: 'Verify code',
    useBackupCode: 'Use backup code instead',
    backupLabel: 'Backup code',
    backupPlaceholder: '••••••••',
  },
}

export type AuthPage = 'sign-in' | 'sign-up' | 'forgot-password' | 'reset-password' | 'verify-email' | 'two-factor'
