import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import { getIntegrationsEnv, isStorageEnabled } from '@/server/config/env'
import { NotImplementedError, ServiceUnavailableError } from '@/server/errors/app-error'

/**
 * Storage service — bytes-level, provider-agnostic contract (Mission 7).
 *
 * This is the low-level adapter: it moves bytes and mints signed URLs, but knows nothing
 * about tenancy or the `FileObject` table (that orchestration lives in `FileService`).
 * The concrete implementation wraps **Supabase Storage** (the same project hosting the
 * DB). Swapping to S3/R2 is a change to this one file. When storage isn't configured, the
 * `Unavailable` implementation refuses calls with a 501, so nothing silently pretends.
 */
export interface SignedUpload {
  /** Signed URL the client PUTs bytes to (direct-to-storage). */
  url: string
  /** Upload token (for `uploadToSignedUrl`). */
  token: string
  path: string
}

export interface StorageService {
  isEnabled(): boolean
  /** Mint a signed direct-to-storage upload URL for `bucket/path`. */
  createUploadUrl(bucket: string, path: string): Promise<SignedUpload>
  /** Short-lived signed download URL for a private object. */
  createSignedUrl(bucket: string, path: string, expiresInSeconds?: number): Promise<string>
  /** Server-side upload of generated bytes (PDFs, QR codes). */
  upload(bucket: string, path: string, bytes: Uint8Array, contentType: string): Promise<void>
  /** Remove an object. */
  remove(bucket: string, path: string): Promise<void>
  /** Whether an object exists (used by commit + regeneration). */
  exists(bucket: string, path: string): Promise<boolean>
  /** Public CDN URL (public bucket only). */
  publicUrl(bucket: string, path: string): string
}

// --- Supabase implementation -------------------------------------------------

export class SupabaseStorageService implements StorageService {
  private client: SupabaseClient | null = null

  private getClient(): SupabaseClient {
    if (this.client) return this.client
    const env = getIntegrationsEnv()
    const key = env.SUPABASE_SERVICE_ROLE_KEY ?? env.SUPABASE_ANON_KEY
    if (!env.SUPABASE_URL || !key) {
      throw new ServiceUnavailableError('Supabase Storage is not configured')
    }
    this.client = createClient(env.SUPABASE_URL, key, {
      auth: { persistSession: false, autoRefreshToken: false },
    })
    return this.client
  }

  isEnabled(): boolean {
    return isStorageEnabled()
  }

  async createUploadUrl(bucket: string, path: string): Promise<SignedUpload> {
    const { data, error } = await this.getClient().storage.from(bucket).createSignedUploadUrl(path)
    if (error || !data) throw new ServiceUnavailableError(`Storage upload URL failed: ${error?.message}`)
    return { url: data.signedUrl, token: data.token, path: data.path }
  }

  async createSignedUrl(bucket: string, path: string, expiresInSeconds?: number): Promise<string> {
    const ttl = expiresInSeconds ?? getIntegrationsEnv().SIGNED_URL_TTL_SEC
    const { data, error } = await this.getClient().storage.from(bucket).createSignedUrl(path, ttl)
    if (error || !data) throw new ServiceUnavailableError(`Signed URL failed: ${error?.message}`)
    return data.signedUrl
  }

  async upload(bucket: string, path: string, bytes: Uint8Array, contentType: string): Promise<void> {
    const { error } = await this.getClient()
      .storage.from(bucket)
      .upload(path, bytes, { contentType, upsert: true })
    if (error) throw new ServiceUnavailableError(`Storage upload failed: ${error.message}`)
  }

  async remove(bucket: string, path: string): Promise<void> {
    const { error } = await this.getClient().storage.from(bucket).remove([path])
    if (error) throw new ServiceUnavailableError(`Storage remove failed: ${error.message}`)
  }

  async exists(bucket: string, path: string): Promise<boolean> {
    const slash = path.lastIndexOf('/')
    const dir = slash >= 0 ? path.slice(0, slash) : ''
    const name = slash >= 0 ? path.slice(slash + 1) : path
    const { data, error } = await this.getClient().storage.from(bucket).list(dir, { search: name })
    if (error) return false
    return (data ?? []).some((o) => o.name === name)
  }

  publicUrl(bucket: string, path: string): string {
    return this.getClient().storage.from(bucket).getPublicUrl(path).data.publicUrl
  }
}

// --- Unavailable fallback ----------------------------------------------------

export class UnavailableStorageService implements StorageService {
  isEnabled(): boolean {
    return false
  }
  private fail(): never {
    throw new NotImplementedError('Storage is not configured (set SUPABASE_URL + a key)')
  }
  async createUploadUrl(): Promise<SignedUpload> {
    return this.fail()
  }
  async createSignedUrl(): Promise<string> {
    return this.fail()
  }
  async upload(): Promise<void> {
    return this.fail()
  }
  async remove(): Promise<void> {
    return this.fail()
  }
  async exists(): Promise<boolean> {
    return false
  }
  publicUrl(): string {
    return this.fail()
  }
}

/** Process-wide storage service — Supabase when configured, else the 501 fallback. */
export const storageService: StorageService = isStorageEnabled()
  ? new SupabaseStorageService()
  : new UnavailableStorageService()
